export const RESTAURANT_ALL = "RESTAURANT_ALL";
export const RESTAURANT_ADD = "RESTAURANT_ADD";
export const RESTAURANT_UPDATE = "RESTAURANT_UPDATE";
export const RESTAURANT_REMOVE = "RESTAURANT_REMOVE";

export const RESTAURANT_USER_ALL = "RESTAURANT_USER_ALL";
export const RESTAURANT_USER_ADD = "RESTAURANT_USER_ADD";
export const RESTAURANT_USER_UPDATE = "RESTAURANT_USER_UPDATE";
export const RESTAURANT_USER_REMOVE = "RESTAURANT_USER_REMOVE";

export const RESTAURANT_EMAIL_ALL = "RESTAURANT_EMAIL_ALL";
export const RESTAURANT_EMAIL_ADD = "RESTAURANT_EMAIL_ADD";
export const RESTAURANT_EMAIL_UPDATE = "RESTAURANT_EMAIL_UPDATE";
export const RESTAURANT_EMAIL_REMOVE = "RESTAURANT_EMAIL_REMOVE";

export const PAYMENT_ALL = "PAYMENT_ALL";
export const PAYMENT_ADD = "PAYMENT_ADD";
export const PAYMENT_UPDATE = "PAYMENT_UPDATE";
export const PAYMENT_REMOVE = "PAYMENT_REMOVE";


export const FOOD_ALL = "FOOD_ALL";
export const FOOD_ADD = "FOOD_ADD";
export const FOOD_UPDATE = "FOOD_UPDATE";
export const FOOD_REMOVE = "FOOD_REMOVE";

export const USERS_ALL = "USERS_ALL";
export const USERS_ADD = "USERS_ADD";
export const USERS_UPDATE = "USERS_UPDATE";
export const USERS_REMOVE = "USERS_REMOVE";


export const NOTIFICATIONS_ALL = "NOTIFICATIONS_ALL";
export const NOTIFICATIONS_ADD = "NOTIFICATIONS_ADD";
export const NOTIFICATIONS_UPDATE = "NOTIFICATIONS_UPDATE";
export const NOTIFICATIONS_REMOVE = "NOTIFICATIONS_REMOVE";


export const FOOD_OPTIONS_ALL = "FOOD_OPTIONS_ALL";
export const FOOD_OPTIONS_ADD = "FOOD_OPTIONS_ADD";
export const FOOD_OPTIONS_UPDATE = "FOOD_OPTIONS_UPDATE";
export const FOOD_OPTIONS_REMOVE = "FOOD_OPTIONS_REMOVE";

export const CATEGOREIS_ALL = "CATEGOREIS_ALL";
export const CATEGOREIS_ADD = "CATEGOREIS_ADD";
export const CATEGOREIS_UPDATE = "CATEGOREIS_UPDATE";
export const CATEGOREIS_REMOVE = "CATEGOREIS_REMOVE";

export const ORDER_ALL = "ORDER_ALL";
export const ORDER_ADD = "ORDER_ADD";
export const ORDER_UPDATE = "ORDER_UPDATE";
export const ORDER_REMOVE = "ORDER_REMOVE";

export const ORDER_FOOD_ALL = "ORDER_FOOD_ALL";
export const ORDER_FOOD_ADD = "ORDER_FOOD_ADD";
export const ORDER_FOOD_UPDATE = "ORDER_FOOD_UPDATE";
export const ORDER_FOOD_REMOVE = "ORDER_FOOD_REMOVE";

export const ORDER_FOOD_OPTIONS_ALL = "ORDER_FOOD_OPTIONS_ALL";
export const ORDER_FOOD_OPTIONS_ADD = "ORDER_FOOD_OPTIONS_ADD";
export const ORDER_FOOD_OPTIONS_UPDATE = "ORDER_FOOD_OPTIONS_UPDATE";
export const ORDER_FOOD_OPTIONS_REMOVE = "ORDER_FOOD_OPTIONS_REMOVE";

export const STOGARE_CART_KEY = "STOGARE_CART_KEY"
export const STOGARE_LIST_FOOD = "STOGARE_LIST_FOOD"
export const STOGARE_RES_ID = "STOGARE_RES_ID"

export const AUTH_SIGN_IN = "AUTH_SIGN_IN"
export const AUTH_SIGN_UP = "AUTH_SIGN_UP"
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT"

//============== Localstorage ==============

export const USER = "USER";
export const HEADERS = "HEADERS";
export const RESTAURANTS = "RESTAURANTS"
export const FOODS = "FOODS"
export const ORDERS = "ORDERS"
export const RESTAURANT_EMAILS = "RESTAURANT_EMAILS"
export const USER_RESTAURANT = "USER_RESTAURANT"

export const GET = 'GET';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const NEW = 'NEW';


